name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Build and publish for all platforms
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Create dist
      run: make all

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: upload-artifact
        retention-days: 5
        path: |
            bin/publish_dist/tmdc-linux-x64
            bin/publish_dist/tmdc-win-x64.exe
            bin/publish_dist/tmdc-linux-arm64
            bin/publish_dist/tmdc-linux-arm

    - name: Upload Assets
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            bin/publish_dist/tmdc-linux-x64
            bin/publish_dist/tmdc-win-x64.exe
            bin/publish_dist/tmdc-linux-arm64
            bin/publish_dist/tmdc-linux-arm
